from __future__ import annotations

import argparse
import json
import subprocess
from copy import deepcopy
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from .cluster_profiles import get_cluster_profile, resolve_cluster_profile_for_server
from .paths import base_ssh_config_path, ensure_state_home, managed_ssh_config_path, registry_path


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_registry() -> dict[str, Any]:
    path = registry_path()
    if not path.exists():
        return {"version": 1, "servers": []}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {"version": 1, "servers": []}
    if not isinstance(data, dict):
        return {"version": 1, "servers": []}
    servers = data.get("servers")
    if not isinstance(servers, list):
        data["servers"] = []
    data.setdefault("version", 1)
    return data


def _save_registry(data: dict[str, Any]) -> None:
    ensure_state_home()
    path = registry_path()
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def _normalize_tags(tags: list[str] | None) -> list[str]:
    if not tags:
        return []
    normalized: list[str] = []
    for raw in tags:
        for tag in raw.split(","):
            tag = tag.strip()
            if tag and tag not in normalized:
                normalized.append(tag)
    return normalized


def _default_server_record(alias: str) -> dict[str, Any]:
    return {
        "alias": alias,
        "host": "",
        "user": "",
        "port": 22,
        "identity_file": None,
        "proxy_jump": None,
        "description": None,
        "tags": [],
        "default_workdir": None,
        "shell": "/bin/bash",
        "cluster_mode": False,
        "scheduler": None,
        "cluster_profile": None,
        "role": None,
        "notes": None,
        "created_at": _now(),
        "updated_at": _now(),
    }


def _find_server(data: dict[str, Any], alias: str) -> tuple[int, dict[str, Any] | None]:
    for index, item in enumerate(data.get("servers", [])):
        if item.get("alias") == alias:
            return index, item
    return -1, None


def _render_config(data: dict[str, Any]) -> str:
    base_config = base_ssh_config_path()
    lines = [
        "# Generated by ssh-skill. Edit servers via ssh_registry.py, not this file.",
        "",
    ]
    if base_config.exists():
        lines.append(f"Include {base_config}")
        lines.append("")
    for server in sorted(data.get("servers", []), key=lambda item: item.get("alias", "")):
        alias = server["alias"]
        lines.append(f"Host {alias}")
        lines.append(f"  HostName {server['host']}")
        if server.get("user"):
            lines.append(f"  User {server['user']}")
        lines.append(f"  Port {int(server.get('port') or 22)}")
        if server.get("identity_file"):
            lines.append(f"  IdentityFile {server['identity_file']}")
        if server.get("proxy_jump"):
            lines.append(f"  ProxyJump {server['proxy_jump']}")
        lines.append("  ServerAliveInterval 15")
        lines.append("  ServerAliveCountMax 3")
        lines.append("  IdentitiesOnly no")
        if server.get("description"):
            lines.append(f"  # description: {server['description']}")
        if server.get("cluster_mode"):
            scheduler = server.get("scheduler") or "unknown"
            lines.append(f"  # cluster_mode: true ({scheduler})")
        if server.get("cluster_profile"):
            lines.append(f"  # cluster_profile: {server['cluster_profile']}")
        if server.get("role"):
            lines.append(f"  # role: {server['role']}")
        tags = server.get("tags") or []
        if tags:
            lines.append(f"  # tags: {', '.join(tags)}")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def _normalize_cluster_profile(cluster_profile: str | None) -> tuple[str | None, dict[str, Any] | None]:
    if cluster_profile is None:
        return None, None
    value = cluster_profile.strip()
    if not value:
        return None, None
    profile = get_cluster_profile(value)["profile"]
    # Store the canonical profile id even when the user passed an alias such as "skd".
    return str(profile.get("id") or value), profile


def _cluster_profile_updates(
    *,
    cluster_profile: str | None,
    cluster_mode: bool | None,
    scheduler: str | None,
) -> dict[str, Any]:
    normalized_profile, profile = _normalize_cluster_profile(cluster_profile)
    updates: dict[str, Any] = {}
    if normalized_profile:
        # A cluster_profile can be bound regardless of cluster_mode. cluster_mode only marks whether
        # a host is treated as a primary scheduler/submission host; debug or compute nodes can still
        # carry the profile for software, policy, and topology context.
        updates["cluster_profile"] = normalized_profile
        if cluster_mode is not None:
            updates["cluster_mode"] = cluster_mode
        if not scheduler and profile and profile.get("scheduler"):
            updates["scheduler"] = profile["scheduler"]
    elif cluster_mode is not None:
        updates["cluster_mode"] = cluster_mode
    if scheduler is not None:
        updates["scheduler"] = scheduler
    return updates


def render_managed_ssh_config() -> Path:
    data = _load_registry()
    ensure_state_home()
    path = managed_ssh_config_path()
    path.write_text(_render_config(data), encoding="utf-8")
    return path


def ensure_state_files() -> dict[str, str]:
    ensure_state_home()
    data = _load_registry()
    _save_registry(data)
    config_path = render_managed_ssh_config()
    return {
        "registry_path": str(registry_path()),
        "managed_ssh_config_path": str(config_path),
        "base_ssh_config_path": str(base_ssh_config_path()),
    }


def list_servers() -> dict[str, Any]:
    data = _load_registry()
    ensure = ensure_state_files()
    servers = []
    for item in sorted(data.get("servers", []), key=lambda server: server.get("alias", "")):
        resolved_profile, resolution_source = resolve_cluster_profile_for_server(item)
        server = deepcopy(item)
        if resolved_profile:
            server["resolved_cluster_profile"] = resolved_profile
            server["cluster_profile_resolution"] = resolution_source
        servers.append(server)
    return {
        "servers": servers,
        **ensure,
    }


def show_server(alias: str) -> dict[str, Any]:
    data = _load_registry()
    _, server = _find_server(data, alias)
    if server is None:
        raise ValueError(f"server not found: {alias}")
    resolved_profile, resolution_source = resolve_cluster_profile_for_server(server)
    payload = deepcopy(server)
    if resolved_profile:
        payload["resolved_cluster_profile"] = resolved_profile
        payload["cluster_profile_resolution"] = resolution_source
    return {
        "server": payload,
        "registry_path": str(registry_path()),
        "managed_ssh_config_path": str(render_managed_ssh_config()),
    }


def get_server_record(alias: str) -> dict[str, Any] | None:
    data = _load_registry()
    _, server = _find_server(data, alias)
    if server is None:
        return None
    return deepcopy(server)


def add_server(
    *,
    alias: str,
    host: str,
    user: str,
    port: int = 22,
    identity_file: str | None = None,
    proxy_jump: str | None = None,
    description: str | None = None,
    tags: list[str] | None = None,
    default_workdir: str | None = None,
    shell: str | None = None,
    cluster_mode: bool = False,
    scheduler: str | None = None,
    cluster_profile: str | None = None,
    role: str | None = None,
    notes: str | None = None,
) -> dict[str, Any]:
    data = _load_registry()
    index, existing = _find_server(data, alias)
    if existing is not None:
        raise ValueError(f"server already exists: {alias}")
    item = _default_server_record(alias)
    cluster_updates = _cluster_profile_updates(
        cluster_profile=cluster_profile,
        cluster_mode=cluster_mode,
        scheduler=scheduler,
    )
    item.update(
        {
            "host": host,
            "user": user,
            "port": port or 22,
            "identity_file": identity_file,
            "proxy_jump": proxy_jump,
            "description": description,
            "tags": _normalize_tags(tags),
            "default_workdir": default_workdir,
            "shell": shell or "/bin/bash",
            "role": role,
            "notes": notes,
            "created_at": _now(),
            "updated_at": _now(),
        }
    )
    item.update(cluster_updates)
    item.setdefault("cluster_mode", bool(cluster_mode))
    item.setdefault("scheduler", scheduler)
    data.setdefault("servers", []).append(item)
    _save_registry(data)
    render_managed_ssh_config()
    return {"server": item}


def update_server(alias: str, *, clear_cluster_profile: bool = False, **updates: Any) -> dict[str, Any]:
    data = _load_registry()
    index, server = _find_server(data, alias)
    if server is None:
        raise ValueError(f"server not found: {alias}")
    cluster_mode_update = updates.pop("cluster_mode", None)
    scheduler_update = updates.get("scheduler")
    cluster_profile_update = updates.pop("cluster_profile", None)
    if clear_cluster_profile:
        server["cluster_profile"] = None
    elif cluster_profile_update is not None:
        cluster_updates = _cluster_profile_updates(
            cluster_profile=cluster_profile_update,
            cluster_mode=cluster_mode_update,
            scheduler=scheduler_update,
        )
        updates.update(cluster_updates)
        cluster_mode_update = None
        scheduler_update = None
    if "tags" in updates and updates["tags"] is not None:
        updates["tags"] = _normalize_tags(updates["tags"])
    if cluster_mode_update is not None:
        updates["cluster_mode"] = cluster_mode_update
    if scheduler_update is not None:
        updates["scheduler"] = scheduler_update
    for key, value in list(updates.items()):
        if value is None:
            updates.pop(key)
    server.update(updates)
    server["updated_at"] = _now()
    data["servers"][index] = server
    _save_registry(data)
    render_managed_ssh_config()
    return {"server": server}


def remove_server(alias: str) -> dict[str, Any]:
    data = _load_registry()
    index, server = _find_server(data, alias)
    if server is None:
        raise ValueError(f"server not found: {alias}")
    del data["servers"][index]
    _save_registry(data)
    render_managed_ssh_config()
    return {"removed": server}


def _ssh_g(alias: str) -> dict[str, str]:
    args = ["ssh", "-G", "-F", str(base_ssh_config_path()), alias]
    try:
        completed = subprocess.run(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=False, timeout=15)
    except (subprocess.TimeoutExpired, FileNotFoundError) as exc:
        raise ValueError(f"failed to inspect ssh alias {alias}: {exc}") from exc
    if completed.returncode != 0:
        raise ValueError(completed.stderr.decode("utf-8", errors="replace").strip() or f"ssh -G failed for {alias}")
    values: dict[str, str] = {}
    for line in completed.stdout.decode("utf-8", errors="replace").splitlines():
        key, _, value = line.partition(" ")
        if key and value:
            values[key.strip().lower()] = value.strip()
    return values


def import_alias(
    alias: str,
    *,
    cluster_mode: bool = False,
    scheduler: str | None = None,
    cluster_profile: str | None = None,
    role: str | None = None,
    description: str | None = None,
    tags: list[str] | None = None,
    notes: str | None = None,
) -> dict[str, Any]:
    values = _ssh_g(alias)
    hostname = values.get("hostname")
    user = values.get("user")
    if not hostname or not user:
        raise ValueError(f"ssh alias {alias} did not resolve host and user")
    port = int(values.get("port") or 22)
    identity_file = values.get("identityfile")
    proxy_jump = values.get("proxyjump")
    data = _load_registry()
    _, existing = _find_server(data, alias)
    payload = dict(
        host=hostname,
        user=user,
        port=port,
        identity_file=identity_file,
        proxy_jump=proxy_jump,
        description=description,
        tags=tags,
        cluster_mode=cluster_mode,
        scheduler=scheduler,
        cluster_profile=cluster_profile,
        role=role,
        notes=notes,
    )
    if existing is None:
        return add_server(alias=alias, **payload)
    return update_server(alias, **payload)


def provision_cluster(
    profile: str,
    *,
    user: str,
    identity_file: str | None = None,
    prefix: str | None = None,
    login_jump_index: int | None = None,
    debug_port: int | None = None,
    dry_run: bool = False,
) -> dict[str, Any]:
    """Register all login and debug hosts for a jump-host cluster profile.

    Login nodes become direct, Slurm-capable submit hosts. Debug nodes are wired with a
    ProxyJump through a login node (because they are only reachable that way) and marked as
    role=debug so the runtime refuses to submit Slurm jobs from them.
    """
    payload = get_cluster_profile(profile)
    prof = payload["profile"]
    profile_id = str(prof.get("id") or profile)
    access = prof.get("access") or {}
    login_nodes = [str(node) for node in (access.get("login_nodes") or []) if str(node).strip()]
    debug_nodes = [str(node) for node in (access.get("debug_nodes") or []) if str(node).strip()]
    if not login_nodes:
        raise ValueError(
            f"cluster profile {profile_id} has no access.login_nodes; cannot provision login/debug hosts"
        )

    login_port = int(access.get("ssh_port") or 22)
    resolved_debug_port = int(debug_port) if debug_port else login_port
    jump_index = login_jump_index if login_jump_index is not None else int(access.get("default_login_jump_index") or 0)
    if jump_index < 0 or jump_index >= len(login_nodes):
        raise ValueError(f"login_jump_index out of range (0..{len(login_nodes) - 1}): {jump_index}")
    requires_jump = bool(access.get("debug_requires_login_jump", True))
    alias_prefix = (prefix or prof.get("host_alias_prefix") or profile_id).strip().strip("-")
    display_name = prof.get("display_name") or profile_id

    login_aliases = [f"{alias_prefix}-login{index}" for index in range(1, len(login_nodes) + 1)]
    jump_alias = login_aliases[jump_index]

    plan: list[dict[str, Any]] = []
    for alias, host in zip(login_aliases, login_nodes):
        plan.append(
            {
                "alias": alias,
                "host": host,
                "port": login_port,
                "role": "login",
                "cluster_mode": True,
                "proxy_jump": None,
                "tags": ["login", profile_id],
                "description": f"{display_name} login node",
            }
        )
    for index, host in enumerate(debug_nodes, start=1):
        alias = f"{alias_prefix}-debug{index}"
        proxy_jump = jump_alias if requires_jump else None
        description = f"{display_name} GPU debug node"
        if proxy_jump:
            description += f" (jump via {jump_alias})"
        plan.append(
            {
                "alias": alias,
                "host": host,
                "port": resolved_debug_port,
                "role": "debug",
                "cluster_mode": False,
                "proxy_jump": proxy_jump,
                "tags": ["debug", profile_id],
                "description": description,
            }
        )

    if dry_run:
        return {
            "dry_run": True,
            "profile": profile_id,
            "user": user,
            "jump_alias": jump_alias,
            "planned_servers": plan,
        }

    results: list[dict[str, Any]] = []
    for record in plan:
        common = dict(
            host=record["host"],
            user=user,
            port=record["port"],
            identity_file=identity_file,
            proxy_jump=record["proxy_jump"],
            description=record["description"],
            tags=record["tags"],
            cluster_mode=record["cluster_mode"],
            scheduler="slurm",
            cluster_profile=profile_id,
            role=record["role"],
        )
        if get_server_record(record["alias"]) is None:
            outcome = add_server(alias=record["alias"], **common)
        else:
            outcome = update_server(record["alias"], **common)
        results.append(outcome["server"])

    render_managed_ssh_config()
    return {
        "profile": profile_id,
        "user": user,
        "jump_alias": jump_alias,
        "login_aliases": login_aliases,
        "servers": results,
        "managed_ssh_config_path": str(managed_ssh_config_path()),
    }


def _print(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, ensure_ascii=False, indent=2))


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Manage ssh-skill server registry")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("list")
    ensure_parser = sub.add_parser("ensure")
    ensure_parser.set_defaults(noop=True)

    show_parser = sub.add_parser("show")
    show_parser.add_argument("alias")

    add_parser = sub.add_parser("add")
    add_parser.add_argument("alias")
    add_parser.add_argument("--host", required=True)
    add_parser.add_argument("--user", required=True)
    add_parser.add_argument("--port", type=int, default=22)
    add_parser.add_argument("--identity-file")
    add_parser.add_argument("--proxy-jump")
    add_parser.add_argument("--description")
    add_parser.add_argument("--tags", nargs="*")
    add_parser.add_argument("--default-workdir")
    add_parser.add_argument("--shell")
    add_parser.add_argument("--cluster-mode", action="store_true")
    add_parser.add_argument("--scheduler")
    add_parser.add_argument("--cluster-profile")
    add_parser.add_argument("--role")
    add_parser.add_argument("--notes")

    update_parser = sub.add_parser("update")
    update_parser.add_argument("alias")
    update_parser.add_argument("--host")
    update_parser.add_argument("--user")
    update_parser.add_argument("--port", type=int)
    update_parser.add_argument("--identity-file")
    update_parser.add_argument("--proxy-jump")
    update_parser.add_argument("--description")
    update_parser.add_argument("--tags", nargs="*")
    update_parser.add_argument("--default-workdir")
    update_parser.add_argument("--shell")
    update_parser.add_argument("--cluster-mode", action="store_true")
    update_parser.add_argument("--no-cluster-mode", action="store_true")
    update_parser.add_argument("--scheduler")
    update_parser.add_argument("--cluster-profile")
    update_parser.add_argument("--clear-cluster-profile", action="store_true")
    update_parser.add_argument("--role")
    update_parser.add_argument("--notes")

    remove_parser = sub.add_parser("remove")
    remove_parser.add_argument("alias")

    import_parser = sub.add_parser("import-alias")
    import_parser.add_argument("alias")
    import_parser.add_argument("--cluster-mode", action="store_true")
    import_parser.add_argument("--scheduler")
    import_parser.add_argument("--cluster-profile")
    import_parser.add_argument("--role")
    import_parser.add_argument("--description")
    import_parser.add_argument("--tags", nargs="*")
    import_parser.add_argument("--notes")

    provision_parser = sub.add_parser(
        "provision-cluster",
        help="Register all login and debug hosts for a jump-host cluster profile (e.g. sist_ai_cluster / skd).",
    )
    provision_parser.add_argument("profile", help="cluster profile id or alias, e.g. sist_ai_cluster or skd")
    provision_parser.add_argument("--user", required=True, help="your cluster account username")
    provision_parser.add_argument("--identity-file", help="private key path used for all hosts")
    provision_parser.add_argument("--prefix", help="alias prefix override (default from the profile, e.g. sist)")
    provision_parser.add_argument(
        "--login-jump-index",
        type=int,
        help="which login node (0-based) debug nodes jump through; default from the profile",
    )
    provision_parser.add_argument("--debug-port", type=int, help="SSH port for debug nodes if it differs from the login port")
    provision_parser.add_argument("--dry-run", action="store_true", help="print the planned hosts without writing the registry")

    sub.add_parser("render")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "list":
            _print(list_servers())
            return 0
        if args.command == "ensure":
            _print(ensure_state_files())
            return 0
        if args.command == "show":
            _print(show_server(args.alias))
            return 0
        if args.command == "add":
            _print(
                add_server(
                    alias=args.alias,
                    host=args.host,
                    user=args.user,
                    port=args.port,
                    identity_file=args.identity_file,
                    proxy_jump=args.proxy_jump,
                    description=args.description,
                    tags=args.tags,
                    default_workdir=args.default_workdir,
                    shell=args.shell,
                    cluster_mode=args.cluster_mode,
                    scheduler=args.scheduler,
                    cluster_profile=args.cluster_profile,
                    role=args.role,
                    notes=args.notes,
                )
            )
            return 0
        if args.command == "update":
            cluster_mode = None
            if args.cluster_mode:
                cluster_mode = True
            if args.no_cluster_mode:
                cluster_mode = False
            _print(
                update_server(
                    args.alias,
                    host=args.host,
                    user=args.user,
                    port=args.port,
                    identity_file=args.identity_file,
                    proxy_jump=args.proxy_jump,
                    description=args.description,
                    tags=args.tags,
                    default_workdir=args.default_workdir,
                    shell=args.shell,
                    cluster_mode=cluster_mode,
                    scheduler=args.scheduler,
                    cluster_profile=args.cluster_profile,
                    clear_cluster_profile=args.clear_cluster_profile,
                    role=args.role,
                    notes=args.notes,
                )
            )
            return 0
        if args.command == "remove":
            _print(remove_server(args.alias))
            return 0
        if args.command == "import-alias":
            _print(
                import_alias(
                    args.alias,
                    cluster_mode=args.cluster_mode,
                    scheduler=args.scheduler,
                    cluster_profile=args.cluster_profile,
                    role=args.role,
                    description=args.description,
                    tags=args.tags,
                    notes=args.notes,
                )
            )
            return 0
        if args.command == "provision-cluster":
            _print(
                provision_cluster(
                    args.profile,
                    user=args.user,
                    identity_file=args.identity_file,
                    prefix=args.prefix,
                    login_jump_index=args.login_jump_index,
                    debug_port=args.debug_port,
                    dry_run=args.dry_run,
                )
            )
            return 0
        if args.command == "render":
            _print({"managed_ssh_config_path": str(render_managed_ssh_config())})
            return 0
    except ValueError as exc:
        print(json.dumps({"error": str(exc)}, ensure_ascii=False, indent=2))
        return 1
    return 0
